name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '8'
      - run: npm install -g bats
      - run: bats -v
      - name: Upload a Build Artifact # <- 새로 추가된 단계 시작
        uses: actions/upload-artifact@v3.1.3
        # with:
        #   name: my-artifact # <- 아티팩트 이름 지정 (원하는 이름으로 변경 가능)
        #   path: path/to/your/files # <- 업로드할 파일/디렉토리의 경로 지정 (실제 경로로 변경 필요)
        #   if-no-files-found: warn # <- 파일을 찾지 못했을 때의 동작 지정
        #   retention-days: 5 # <- 아티팩트의 유지 기간을 일 단위로 설정 (원하는 기간으로 변경 가능)
